### ISSUE TITLE
Feature: Modal stacking shouldn't be a default behaviour

### ISSUE THREAD

**Issue by smashercosmo** [myaskevich/react-redux-modal-provider#2]
Hey, thx for a nice approach to handling modals in react/redux applications. Works like a charm. However, it seems to me that stacking behaviour is not the one that people need by default. In most of the apps you need only one modal window opened at a time. So I propose at least create an option to change behaviour and at most make it default.

**Comment by mayask** [comment]
Hey

Thanks. Glad you found it useful!

I agree there should be an easy way to provide the "one-modal-at-a-time" functionality. However I don't think making it the default behavior is the best way to do it ;)

So `oneModalAtATime={true}` option should be a good compromise.

I will look into that this weekend and let you know when it's done. Stay tuned.

**Comment by mayask** [comment]
Hey @smashercosmo 

Good news! Just published `v1.1.0` shipping single mode provider. Check out [`<SingleModalProvider>`](https://github.com/myaskevich/react-redux-modal-provider#singlemodalprovider) example for details.

Let me know what you think.

**Comment by smashercosmo** [comment]
First of all thx for quick update, appreciate it) However, I checked the implementation and it looks like a bit overengineered to me. I mean all this stuff like using eventemitter, inhereting from base provider, hiding modal in componentWillReceiveProps and so on... I have a strong feeling, that all of this could be simplified and could be rewritten in a more react/redux-ish way. I don't have a clear picture of how this should be implemented, just some ideas (good or bad I don't know yet). If you'd like to we can have skype call to discuss what could be done to make things awesome))

**Comment by mayask** [comment]
@smashercosmo thanks for your feedback.

You can still use `v1.1.1` that doesn't make use of eventemitter stuff.

The `v2` branch is out of scope of this issue and might not go along with your initial ideas.

I'd appreciate you post your thoughts on how we could improve it, once you find time ;)

If you think `v1.1.1` does solve your original problem, please consider closing this issue.

Best regards
